export type EventItem = {
  slug: string;
  title: string;
  date: string;
  venue: string;
  category: string;
  description: string;
  body: string[];
  image: { url: string; alt: string };
};

export const events: EventItem[] = [
  {
    slug: "south-thames-regional-connect-7057",
    title: "South Thames Regional Connect",
    date: "18 Jun 2026",
    venue: "Worplesdon Place Pub",
    category: "BALI Regional Event",
    description: "Following the success of the January event, join the South Thames committee for our second Regional Connect of 2026.",
    body: [
      "Following the success of the January event, join the South Thames committee for our second Regional Connect of 2026.",
      "An ideal opportunity for members who have joined in last 3 years to learn more about BALI and meet the committee lead by Chair, Brian Herbert (Outdoor Options) alongside Vice Chair, Charles Blumlein (Location Landscapes) who are both keen to provide members with the opportunity to network and support one another.",
      "If you haven’t yet attended a regional event why not come along and get to know others in an informal setting whilst building better relationships.",
      "This event is £10 per person with tea and coffee included. Other drinks and food will be available to order and to be paid for, individually, on the day.",
      "On the dayArrival: 6.00pm - Join Brian as he leads the Regional Connect to discuss business challenges, solutions and what is being planned for 2026 and beyond.",
      "7.30/8.00pm onwards – You are welcome to stay for food (optional) and networking – please note food and additional drinks are not included and must be paid for individually.",
      "standard £10.00* * All prices are inclusive of VAT",
    ],
    image: { url: "/__l5e/assets-v1/ddcf24fe-2b85-4446-9a78-a492174c7901/worplesdon-pub-800x500.png", alt: "South Thames Regional Connect" },
  },
  {
    slug: "midlands-regional-event--sky-garden-7041",
    title: "Midlands Regional Event – Sky Garden",
    date: "18 Jun 2026",
    venue: "Sky Garden, Wick Production Unit",
    category: "BALI Regional Event",
    description: "Join us for this informative and educational Midlands regional event, hosted by Sky Garden, featuring an Urban Greening CPD, a hands-on training session using the training rig and a guided tour of the farm with discussion around wildflower production, harvesting, maintenance and applications for BNG.",
    body: [
      "Join us for this informative and educational Midlands regional event, hosted by Sky Garden, featuring an Urban Greening CPD, a hands-on training session using the training rig and a guided tour of the farm with discussion around wildflower production, harvesting, maintenance and applications for BNG.",
      "standard £15.00* member price",
      "standard £10.00* * All prices are inclusive of VAT",
    ],
    image: { url: "/__l5e/assets-v1/cb3c5a46-926a-46e3-b787-07941df835b4/cascade-tower.png", alt: "Midlands Regional Event – Sky Garden" },
  },
  {
    slug: "yorkshire-and-north-east--newby-hall-event-7140",
    title: "Yorkshire & North East – Newby Hall Event",
    date: "24 Jun 2026",
    venue: "Newby Hall & Gardens",
    category: "BALI Regional Event",
    description: "Join the Yorkshire & North East committee for another fantastic event.",
    body: [
      "Following on from the recent golf day at Rudding Park, we are looking forward to hosting a day of inspiration, insight and connection at the stunning Newby Hall, Ripon.",
      "Dean Bolton-Grant, an award-winning designer and landscaper, will be sharing his expertise and perspective on creating exceptional outdoor spaces - bringing both creative and commercial insight to the day.",
      "The experience will also include:",
      "A talk from Lee Bestall from Bestall & Co on the industry and the next decadeA guided tour of the renowned Newby Hall gardens, led by the Head Gardener Lawrence WrightA relaxed networking lunch in a truly inspiring settingThis event is designed to bring together like-minded professionals from across the landscaping and design community - offering inspiration, practical insight, and the chance to connect in one of the UK’s most beautiful horticultural environments.",
      "You will also have the opportunity to explore Urban Grow’s carefully curated range of premium gardening and outdoor living products, sourced from across Britain and Europe with a focus on quality and sustainability.",
      "11.00am - 11.30am - Welcome and coffees",
      "11.30am – 12.15pm - Dean Bolton-Grant, Urban Grow Talk",
      "12.15pm – 1.00pm – Lee Bestall, Bestall & Co – The Landscaper is dead/Why the Next Decade Belongs to Social Media Companies That Build Gardens",
      "1.30pm – 2.00pm - Lunch, cold buffet lunch 2 courses",
      "2.00pm – 3.30pm - Tour of gardens with Newby Hall Head Gardener, Lawrence Wright",
      "3.30pm – 4.30pm - Networking at Urban Grow showroom",
      "Urban Grow, curators of premium gardening and outdoor living products, combine quality, sustainability, and thoughtful design. Working with trusted manufacturers and growers across Britain and Europe, they source products that help transform outdoor spaces - whether that’s a compact urban terrace or a large-scale landscape project.",
      "Beyond supplying exceptional products, Urban Grow works closely with a network of allied industries, including landscapers, designers, developers, and hospitality professionals to support the successful delivery of their projects. Through these partnerships, they offer preferential rates and tailored sourcing solutions, helping our clients improve margins without compromising on quality or sustainability.",
      "Their approach is collaborative and commercially focused: providing access to carefully selected products that elevate the end result. By bridging the gap between supply and application, Urban Grow enables their partners to deliver better outdoor spaces - more efficiently and more profitably.",
      "Driven by a passion for modern horticulture and responsible sourcing, Urban Grow is committed to making high-quality outdoor living more accessible, while supporting the professionals who bring these spaces to life.",
      "Lee Bestall is an award-winning British garden designer, entrepreneur and educator, best known as the founder and creative force behind Bestall & Co Landscape Design, the Sheffield-based landscape design studio recognised for creating some of the North of England’s most distinctive residential gardens. Often referred to as “The Northern Designer”, Lee has built a reputation for combining bold geometry, immersive planting and atmospheric lighting to create outdoor spaces that transform the way people live and interact with their homes. His work has earned awards at RHS flower shows including Chelsea, winning his first RHS Gold in his home town during RHS Wentworth 2025.",
      "Over the past two decades, Lee and his team at Bestall & Co have developed a multi-award-winning practice specialising in premium garden design, planting and landscape transformation across Yorkshire, Derbyshire and Nottinghamshire. Alongside his design work, Lee has become a respected voice within the gardening industry through television, radio, public speaking and his growing social media platform, where he shares practical, accessible advice to inspire a wider audience to engage with garden design. His approach blends creative ambition with real-world usability, championing landscapes that are not only visually striking, but deeply personal and made to be lived in.",
      "Lawrence Wright",
      "Trained at Brooksby Melton College, Chatsworth House and RHS Garden Wisley. Charter Institute of Horticulture Young Horticulturist of the Year in 2016. Head Gardener at Newby Hall since October 2021. Additionally, a member of RHS Tender Ornamental Expert Group and Harrogate Flower Show Judge.",
    ],
    image: { url: "/__l5e/assets-v1/98d07389-8b3f-483f-86db-f10e2d0c9a1b/yne-newby-hall-800x500.png", alt: "Yorkshire & North East – Newby Hall Event" },
  },
  {
    slug: "east-anglia-event--natural-swimming-pools-7105",
    title: "Tom Hoblyn's Kitchen Garden, Natural Swimming Pools and Rymer Trees Nursery Event",
    date: "25 Jun 2026",
    venue: "Various locations",
    category: "BALI Regional Event",
    description: "Join the East Anglia Committee for a day of fun, learning and visits to various locations. Venues - Rymer Trees & Hedging Nursery, The Grumpy Goat Café, Tom Hoblyn’s Kitchen Garden, Kate Miller’s garden with Natural Swimming Pool",
    body: [
      "The day will start with a visit to Rymer Trees & Fencing Nursery, which is completely peat free. The day will include a talk and tour by Chelsea and Hampton Court award winning designer Tom Hoblyn of his kitchen garden. After a stop off for lunch we will then take a visit to Kate Miller’s very own Natural Swimming Pools pool. The day will finish off with a barbecue and dip (optional), hosted by Kate.",
      "This event will provide plenty of opportunity for networking throughout the day, so be sure to book your tickets.",
      "10:30am – 11:00am - Arrival at The Grumpy Goat Café, Bardwell",
      "11:00am – 12:30pm – Tour and Talk with Harry, Rymer Trees & Hedging Nursery",
      "12:30pm – 1.45pm – Café Lunch, Lunch, The Grumpy Goat Café, Bardwell Village",
      "2.00pm – 3.30pm – Tour and Talk from multiple Chelsea and Hampton Court award winner, Tom Hoblyn, of his kitchen garden and sustainable plant garden.",
      "3.35pm – 4.00pm - Natural Swimming Pools Talk, Kate Miller",
      "4.00pm – 6.30pm – BBQ, Social & Networking at Kate’s house (food and drinks provided by Kate Miller, Natural Swimming Pools). Swimming is optional but please bring your own swimwear and towels if you plan to take a dip!",
      "Natural Swimming Pools",
      "Natural Swimming Pools Ltd. have been building and maintaining natural swimming pools since 2001. Before that they built up a wealth of experience as landscape gardeners, transforming outdoor spaces and building stunning water features. They now work all over the UK and overseas and their pools regularly feature on TV and in lifestyle magazines.",
      "They currently operate from an office in East Anglia but cover the entire UK and have also completed projects in mainland Europe.",
      "Their team consists of skilled builders, landscapers and plant specialists. As part of their service they can provide a complete planning, construction and aftercare service and can tailor every aspect of the design to your personal preferences.",
      "standard £25.00* member price",
      "standard £20.00* * All prices are inclusive of VAT",
    ],
    image: { url: "/__l5e/assets-v1/0821e182-b46b-4792-a3a4-0bf64c143f8c/ea-natural-swimming-pools-event-800x500.png", alt: "Tom Hoblyn's Kitchen Garden, Natural Swimming Pools and Rymer Trees Nursery Event" },
  },
  {
    slug: "southwest-regional-connect--human-performance-in-landscaping-7104",
    title: "Southwest Regional Connect – Human Performance in Landscaping",
    date: "02 Jul 2026",
    venue: "The Manor House Inn",
    category: "BALI Regional Event",
    description: "Join us at the Manor Inn, Ditcheat for a relaxed Southwest Connect event focused on human performance in the landscaping industry",
    body: [
      "We’ll explore the physical and mental demands of the job, from manual handling and extreme weather to hydration, nutrition, and overall wellbeing.",
      "Supporting the session will be Chris Giles, an ex-professional footballer, GB triathlete, now a Movement & Wellness Coach. He works with individuals from gardeners to business leaders, helping improve performance, build resilience, and support long-term wellbeing through a practical, holistic approach to habits and mindset.",
      "5.30pm – Arrival and informal pub meet with Movement & Wellness Coach, Chris Giles, an ex-professional footballer, GB triathlete.",
      "7.30pm – Finish",
      "* Please note, refreshments are not provided and participants must settle their own bill during the evening.",
    ],
    image: { url: "/__l5e/assets-v1/e43d37dd-aa80-4426-8b26-f0bc047c6525/manor-inn-event-800x500.png", alt: "Southwest Regional Connect – Human Performance in Landscaping" },
  },
  {
    slug: "north-thames-and-east-anglia-beth-chatto-gardens-event-7155",
    title: "North Thames & East Anglia Beth Chatto Gardens Event",
    date: "07 Jul 2026",
    venue: "Beth Chatto Plants & Gardens",
    category: "BALI Regional Event",
    description: "We have a fantastic collaborative event planned for both the North Thames and East Anglia region in July.",
    body: [
      "Join us in the height of Summer to explore and learn about the world renowned gardens and extensive plant nursery, created by award winning plants woman Beth Chatto OBE.",
      "On the day we will split everyone into smaller groups depending on numbers with the day as follows:",
      "Garden tour: exploring the renowned Beth Chatto Gardens: 7.5 acres of ecological, informal gardens based on Beth Chatto’s famous principle of right plant, right place. This tour will be accompanied by one of the Garden team and Dr Chris Gibson who will give the wildlife benefits of the garden.",
      "Nursery tour behind the scenes: join a member of our propagation department behind the scenes, looking at how we produce our plants from seed, cuttings and division, all grown in peat-free soil This will also incorporate Widening your plant palette talk – an opportunity to expand your plant palette. We’ll look at the drought resistant, wildlife friendly plant palette we use for external projects.",
      "History of Beth Chatto Gardens and External projects talk: find out more about how we’ve been bringing ecological and sustainable gardening to public spaces in our local area, including Chattowood, a nearby housing development, and the Meanwhile Garden, a former brownfield site transformed into a public pocket-park. Including time for Q&A",
      "10.00am – Arrival, tea & coffee in Willow Room",
      "10.20am – Welcome by Noel Brock, Frognal Gardens and North Thames Regional Chair",
      "10.30am – Garden Tour First Session (each group, split into A/B/C will go according to their timetable",
      "11.45am – Nursery tour behind the scenes - Second session (each group, split into A/B/C will go according to their timetable",
      "12:45pm – Lunch, vegetarian buffet",
      "1.30pm – History of Beth Chatto Gardens and External projects talk - Third Session (each group, split into A/B/C will go according to their timetable",
      "2.45pm – Free time to further explore the gardens and do a “LoveBug” bio-blitz with Noel and Caroline (if the weather permits!)",
      "About the gardens",
      "Beth Chatto’s Plants & Gardens, near Colchester in Essex, comprise 7.5 acres of inspirational, world-renowned gardens created by Beth Chatto OBE VMH, one of the most influential gardeners of the modern era.",
      "Guided by her husband Andrew Chatto’s life-long study into the homes of garden plants and their preferred natural habits, the gardens are designed around the principle of “the right plant for the right place”. What began as a challenging, unpromising site - boggy in parts and extremely try and infertile in others – in one of the driest parts of the UK, has been transformed into a series of informal gardens where five distinct areas demonstrate how plants thrive when matched to their preferred growing conditions.",
      "The Gravel Garden, created in the early 1990’, began as an experiment to prove that a garden with poor, free-draining soil can flourish without irrigation, when planted thoughtfully. The raised beds of the Scree Garden are home to species that naturally inhabit mountainsides and other harsh environments, thriving in low-fertility conditions with sharp drainage. In contrast, the tranquil Water Garden occupies a naturally boggy hollow with richer soil, allowing lush, moisture-loving plants to flourish. Beyond it, the Reservoir Garden spreads across a gentle south-facing slope, showcases a dynamic tapestry of perennials and ornamental grasses. The Woodland Garden offers dappled light beneath a canopy of mature oaks, with carpets of groundcovers weaving between shade-loving bulbs, perennials, ferns and shrubs.",
      "Beside the gardens, the adjacent nursery offers more than 2,000 different varieties of plants, most of them herbaceous perennials, produced and grown on site in peat-free compost. Visitors can also enjoy a giftshop and a tearoom serving light refreshments.",
      "Beth Chatto’s Plant & Gardens champions ecological gardening and sustainable planting, with strong focus on biodiversity and water-wise planting. We are passionate about extending these principles to the public landscape.",
      "Our recent external projects include drought-resistant landscaping at Chattowood, a local housing development, and the Albert roundabout in Colchester. Both designs apply the principle of planting directly into sand to create resilient planting schemes that require minimal care and thrive without irrigation. We are also work with local councils to advise on sustainable, climate-resilient planting strategies for public spaces.",
      "The Beth Chatto team",
    ],
    image: { url: "/__l5e/assets-v1/54794fa7-5645-4688-849a-6d6bfa927889/nt-ea-chatto-event-800x500.png", alt: "North Thames & East Anglia Beth Chatto Gardens Event" },
  },
  {
    slug: "supplier-forum-event-the-way-of-the-modern-world-how-to-build-a-7016",
    title: "Supplier Forum: The way of the modern world, how to build a better business",
    date: "16 Jul 2026",
    venue: "STIHL",
    category: "Supplier Forum",
    description: "The Supplier Forum are pleased to announce their next event is to be held at STIHL GB’s state-of-the-art office distribution centre. For this event we wanted to ensure delegates attending come away feeling inspired and have ideas they can put into action within their own businesses.",
    body: [
      "BALI National Event",
      "The Supplier Forum are pleased to announce their next event is to be held at STIHL GB’s state-of-the-art office distribution centre. For this event we wanted to ensure delegates attending come away feeling inspired and have ideas they can put into action within their own businesses.",
      "Kay Green, STIHL’s MD will start the day talking about the importance of a robust People Strategy. Kim Sones, MD of Sones Accountancy will follow on to speak about taking control of late payments and cash flow.",
      "The two talks after lunch will be delivered from Jon Berry, MD of Tyler Grange who will be speaking about recruitment and B Corp certification, and Oliver Wood, Joe’s Blooms will finish with a talk about the digital tool built to help people measure BNG and how to use tech in an innovative way in the industry.",
      "Alongside the day will be a tour and demo from STIHL and plenty of time to network together!",
      "This is set to be a sell out event – make sure you don’t miss out and book your place today!",
      "10:00am Welcome and refreshments",
      "10.30am STIHL intro and talk Kay Green, Managing Director",
      "11.15am Kim Sones, Sones Accountancy - Taking Control of Late Payments and Protecting Your Cash Flow",
      "12.00pm Buffet Lunch",
      "12:30pm STIHL tour and demo, Darren Summerley and David Tingle",
      "1.30pm John Berry, Tyler Grange - Recruitment talk and B Corp Certification",
      "2.15pm Oliver Lewis from Joe’s Bloom - BNG best practice and emerging trends",
      "3-3.30pm Finish",
      "Ever since Andreas Stihl invented the first portable chainsaw, the STIHL name has stood for revolutionary technology, driven by significant investments in research and development and a single-minded passion for making people’s lives easier when working in nature. It’s because of this that STIHL has been the world’s best-selling petrol chainsaw brand since 1971.",
      "This event, hosted by STIHL Great Britain, will deliver insights from STIHL’s experts about the newest tools and what to expect from STIHL in the future. They will share key information about battery charging, storage and management to help you understand how and when you can make the transition to battery tools. You’ll also get to see STIHL’s latest battery products in action. Finally, you’ll get a behind-the-scenes tour of the state-of-the-art distribution centre and office facility to see how STIHL supports their network of 750 STIHL Approved Dealers across Great Britain.",
      "Sones Accountancy",
      "Kim Sones is the Managing Director of Sones Accountancy Services Ltd, a specialist accountancy practice supporting landscaping businesses across the UK. Kim is passionate about helping business owners truly understand their numbers so they can make better decisions, improve profitability, and take control of their cash flow. Her approach goes beyond compliance as she works closely with clients to move them from reactive firefighting to proactive financial management.",
      "Through a combination of technology, advisory services, and practical education, Kim helps directors gain clarity on their financial position, improve cash flow, and build more resilient, profitable businesses. She is a regular speaker within the landscaping industry and is known for delivering clear, practical advice that business owners can implement immediately.",
      "Late payments are a common challenge in the landscaping industry, but they’re often accepted as “just part of the job. In this session, Kim Sones will challenge that thinking and show how late payments are not just a nuisance, but a key driver of poor cash flow and unnecessary financial stress.",
    ],
    image: { url: "/__l5e/assets-v1/3942b6a0-ada0-4e11-ae64-cc9f78fe63d2/supplier-forum16july-800x500.png", alt: "Supplier Forum: The way of the modern world, how to build a better business" },
  },
  {
    slug: "bali-chalk-open-mic-night-7157",
    title: "BALI Chalk Fund Landscape Open Mic Night",
    date: "01 Oct 2026",
    venue: "Spice of Life Bar",
    category: "BALI Chalk Fund",
    description: "This Autumn, the BALI Chalk team is hosting an Open Mic evening at the Spice of Life Bar, Soho, London on Thursday 1 October 2026. The venue has seen legendary performances from the likes of Bob Dylan, The Who, The Stranglers, Sex Pistols and Spandau Ballet over its rich musical history - and you could be next!",
    body: [
      "Keeping a hidden talent under wraps? Why not show us what you've got?",
      "BALI Chalk Landscape Open Mic NightThurs 1 October 2026, Spice of Life, Soho, with the BALI Chalk FundTickets: £50",
      "We already know what an amazing spectrum of talent we have in the UK landscape sector. At BALI Chalk Fund, we celebrate this every year in our Student Awards and the provision of over £35,000 enrichment grants to land-based colleges to make sure that throughput of talent keeps translating into work-ready employees, embarking on their careers in the UK landscape sector.",
      "But what other hidden talents are you hiding?",
      "We’re looking to find out! Can you, or someone you know, belt out a blinding tune? Perhaps there’s a closet Clapton or cloak-and-dagger Jagger amongst you? Then this is your chance to show us what you've got.",
      "Follow in the footsteps of the legends of music",
      "This Autumn, the BALI Chalk team is hosting an Open Mic evening at the Spice of Life Bar, Soho, London on Thursday 1 October 2026. The venue has seen legendary performances from the likes of Bob Dylan, The Who, The Stranglers, Sex Pistols and Spandau Ballet over its rich musical history - and you could be next!",
      "Sponsored by Gold Champion Elmtree Landscapes, the event is open to all BALI Chalk Champions, Award Winners and Colleges but of course, we are welcoming anyone from the wider UK landscape, horticulture and garden design sectors – it’s your time to shine.",
      "Funding skills and training for future landscape, design and horticultural promise",
      "A cracker at karaoke? A secret saxophonist? A guerilla guitarist? Masked maracas enthusiast?! This is your chance to show us what you've got on stage, putting the fun into fundraising and helping boost the Fund for future landscape generations.",
      "The evening will be ticketed at £50 per person, which will include a buffet and one drink token. You’ll also be able to purchase Vote Tokens on the night to nominate your favourite act.",
      "It doesn’t matter if you’re tentative on the tambourine, a whizz on the penny whistle or a covert keyboard player – let’s get you on that stage.",
      "Book your tickets and performance slots",
      "Sponsorship opportunities are also available.",
      "Email Diane McCulloch - diane.mcculloch@balichalkfund.org.uk - to find out about sponsorship and performing.",
      "To book your tickets for this live interactive event in October, go to the BALI Chalk website.",
      "Venue numbers are limited, so bag your spot early!",
    ],
    image: { url: "/__l5e/assets-v1/21237f3e-3ed1-47eb-b919-bc6ac788dff9/bcf-open-mic-flyer-2026-1200-x-627-px-.jpg", alt: "BALI Chalk Fund Landscape Open Mic Night" },
  },
];

export function getEvent(slug: string): EventItem | undefined {
  return events.find((e) => e.slug === slug);
}