/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PolicyIndexRouteImport } from './routes/policy.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as DirectoryIndexRouteImport } from './routes/directory.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PolicySlugRouteImport } from './routes/policy.$slug'
import { Route as NewsMagazineRouteImport } from './routes/news.magazine'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as HelpPodcastRouteImport } from './routes/help.podcast'
import { Route as HelpPlantHealthRouteImport } from './routes/help.plant-health'
import { Route as HelpPestsRouteImport } from './routes/help.pests'
import { Route as HelpLawRouteImport } from './routes/help.law'
import { Route as HelpHealthSafetyRouteImport } from './routes/help.health-safety'
import { Route as HelpHardshipRouteImport } from './routes/help.hardship'
import { Route as HelpGuidesRouteImport } from './routes/help.guides'
import { Route as HelpEquipmentRouteImport } from './routes/help.equipment'
import { Route as HelpDomesticLandscapeContractRouteImport } from './routes/help.domestic-landscape-contract'
import { Route as HelpDisputeRouteImport } from './routes/help.dispute'
import { Route as HelpContractRouteImport } from './routes/help.contract'
import { Route as EventsTrainingRouteImport } from './routes/events.training'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as DirectoryWhyRouteImport } from './routes/directory.why'
import { Route as DirectoryTrainingRouteImport } from './routes/directory.training'
import { Route as DirectorySupplierRouteImport } from './routes/directory.supplier'
import { Route as DirectorySearchRouteImport } from './routes/directory.search'
import { Route as DirectoryDesignerRouteImport } from './routes/directory.designer'
import { Route as DirectoryContractorRouteImport } from './routes/directory.contractor'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AboutAwardsRouteImport } from './routes/about.awards'
import { Route as AdminTrainingIndexRouteImport } from './routes/admin.training.index'
import { Route as AdminPolicyIndexRouteImport } from './routes/admin.policy.index'
import { Route as AdminNewsIndexRouteImport } from './routes/admin.news.index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as JoinCategoryApplyRouteImport } from './routes/join.$category.apply'
import { Route as ApiPublicMembershipApplicationRouteImport } from './routes/api/public/membership-application'
import { Route as ApiPublicConferenceInterestRouteImport } from './routes/api/public/conference-interest'
import { Route as AdminTrainingIdRouteImport } from './routes/admin.training.$id'
import { Route as AdminPolicyIdRouteImport } from './routes/admin.policy.$id'
import { Route as AdminNewsIdRouteImport } from './routes/admin.news.$id'
import { Route as AdminEventsIdRouteImport } from './routes/admin.events.$id'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyIndexRoute = PolicyIndexRouteImport.update({
  id: '/policy/',
  path: '/policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PolicySlugRoute = PolicySlugRouteImport.update({
  id: '/policy/$slug',
  path: '/policy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsMagazineRoute = NewsMagazineRouteImport.update({
  id: '/news/magazine',
  path: '/news/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpPodcastRoute = HelpPodcastRouteImport.update({
  id: '/help/podcast',
  path: '/help/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpPlantHealthRoute = HelpPlantHealthRouteImport.update({
  id: '/help/plant-health',
  path: '/help/plant-health',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpPestsRoute = HelpPestsRouteImport.update({
  id: '/help/pests',
  path: '/help/pests',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpLawRoute = HelpLawRouteImport.update({
  id: '/help/law',
  path: '/help/law',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpHealthSafetyRoute = HelpHealthSafetyRouteImport.update({
  id: '/help/health-safety',
  path: '/help/health-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpHardshipRoute = HelpHardshipRouteImport.update({
  id: '/help/hardship',
  path: '/help/hardship',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpGuidesRoute = HelpGuidesRouteImport.update({
  id: '/help/guides',
  path: '/help/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpEquipmentRoute = HelpEquipmentRouteImport.update({
  id: '/help/equipment',
  path: '/help/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDomesticLandscapeContractRoute =
  HelpDomesticLandscapeContractRouteImport.update({
    id: '/help/domestic-landscape-contract',
    path: '/help/domestic-landscape-contract',
    getParentRoute: () => rootRouteImport,
  } as any)
const HelpDisputeRoute = HelpDisputeRouteImport.update({
  id: '/help/dispute',
  path: '/help/dispute',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpContractRoute = HelpContractRouteImport.update({
  id: '/help/contract',
  path: '/help/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsTrainingRoute = EventsTrainingRouteImport.update({
  id: '/events/training',
  path: '/events/training',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryWhyRoute = DirectoryWhyRouteImport.update({
  id: '/directory/why',
  path: '/directory/why',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryTrainingRoute = DirectoryTrainingRouteImport.update({
  id: '/directory/training',
  path: '/directory/training',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorySupplierRoute = DirectorySupplierRouteImport.update({
  id: '/directory/supplier',
  path: '/directory/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorySearchRoute = DirectorySearchRouteImport.update({
  id: '/directory/search',
  path: '/directory/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryDesignerRoute = DirectoryDesignerRouteImport.update({
  id: '/directory/designer',
  path: '/directory/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryContractorRoute = DirectoryContractorRouteImport.update({
  id: '/directory/contractor',
  path: '/directory/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AboutAwardsRoute = AboutAwardsRouteImport.update({
  id: '/about/awards',
  path: '/about/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingIndexRoute = AdminTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolicyIndexRoute = AdminPolicyIndexRouteImport.update({
  id: '/policy/',
  path: '/policy/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const JoinCategoryApplyRoute = JoinCategoryApplyRouteImport.update({
  id: '/$category/apply',
  path: '/$category/apply',
  getParentRoute: () => JoinRoute,
} as any)
const ApiPublicMembershipApplicationRoute =
  ApiPublicMembershipApplicationRouteImport.update({
    id: '/api/public/membership-application',
    path: '/api/public/membership-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConferenceInterestRoute =
  ApiPublicConferenceInterestRouteImport.update({
    id: '/api/public/conference-interest',
    path: '/api/public/conference-interest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTrainingIdRoute = AdminTrainingIdRouteImport.update({
  id: '/training/$id',
  path: '/training/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolicyIdRoute = AdminPolicyIdRouteImport.update({
  id: '/policy/$id',
  path: '/policy/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsIdRoute = AdminNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/about/awards': typeof AboutAwardsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/directory/contractor': typeof DirectoryContractorRoute
  '/directory/designer': typeof DirectoryDesignerRoute
  '/directory/search': typeof DirectorySearchRoute
  '/directory/supplier': typeof DirectorySupplierRoute
  '/directory/training': typeof DirectoryTrainingRoute
  '/directory/why': typeof DirectoryWhyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/training': typeof EventsTrainingRoute
  '/help/contract': typeof HelpContractRoute
  '/help/dispute': typeof HelpDisputeRoute
  '/help/domestic-landscape-contract': typeof HelpDomesticLandscapeContractRoute
  '/help/equipment': typeof HelpEquipmentRoute
  '/help/guides': typeof HelpGuidesRoute
  '/help/hardship': typeof HelpHardshipRoute
  '/help/health-safety': typeof HelpHealthSafetyRoute
  '/help/law': typeof HelpLawRoute
  '/help/pests': typeof HelpPestsRoute
  '/help/plant-health': typeof HelpPlantHealthRoute
  '/help/podcast': typeof HelpPodcastRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/magazine': typeof NewsMagazineRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/help/': typeof HelpIndexRoute
  '/news/': typeof NewsIndexRoute
  '/policy/': typeof PolicyIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/policy/$id': typeof AdminPolicyIdRoute
  '/admin/training/$id': typeof AdminTrainingIdRoute
  '/api/public/conference-interest': typeof ApiPublicConferenceInterestRoute
  '/api/public/membership-application': typeof ApiPublicMembershipApplicationRoute
  '/join/$category/apply': typeof JoinCategoryApplyRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/policy/': typeof AdminPolicyIndexRoute
  '/admin/training/': typeof AdminTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/about/awards': typeof AboutAwardsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/directory/contractor': typeof DirectoryContractorRoute
  '/directory/designer': typeof DirectoryDesignerRoute
  '/directory/search': typeof DirectorySearchRoute
  '/directory/supplier': typeof DirectorySupplierRoute
  '/directory/training': typeof DirectoryTrainingRoute
  '/directory/why': typeof DirectoryWhyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/training': typeof EventsTrainingRoute
  '/help/contract': typeof HelpContractRoute
  '/help/dispute': typeof HelpDisputeRoute
  '/help/domestic-landscape-contract': typeof HelpDomesticLandscapeContractRoute
  '/help/equipment': typeof HelpEquipmentRoute
  '/help/guides': typeof HelpGuidesRoute
  '/help/hardship': typeof HelpHardshipRoute
  '/help/health-safety': typeof HelpHealthSafetyRoute
  '/help/law': typeof HelpLawRoute
  '/help/pests': typeof HelpPestsRoute
  '/help/plant-health': typeof HelpPlantHealthRoute
  '/help/podcast': typeof HelpPodcastRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/magazine': typeof NewsMagazineRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/admin': typeof AdminIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/events': typeof EventsIndexRoute
  '/help': typeof HelpIndexRoute
  '/news': typeof NewsIndexRoute
  '/policy': typeof PolicyIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/policy/$id': typeof AdminPolicyIdRoute
  '/admin/training/$id': typeof AdminTrainingIdRoute
  '/api/public/conference-interest': typeof ApiPublicConferenceInterestRoute
  '/api/public/membership-application': typeof ApiPublicMembershipApplicationRoute
  '/join/$category/apply': typeof JoinCategoryApplyRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/policy': typeof AdminPolicyIndexRoute
  '/admin/training': typeof AdminTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/about/awards': typeof AboutAwardsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/directory/contractor': typeof DirectoryContractorRoute
  '/directory/designer': typeof DirectoryDesignerRoute
  '/directory/search': typeof DirectorySearchRoute
  '/directory/supplier': typeof DirectorySupplierRoute
  '/directory/training': typeof DirectoryTrainingRoute
  '/directory/why': typeof DirectoryWhyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/training': typeof EventsTrainingRoute
  '/help/contract': typeof HelpContractRoute
  '/help/dispute': typeof HelpDisputeRoute
  '/help/domestic-landscape-contract': typeof HelpDomesticLandscapeContractRoute
  '/help/equipment': typeof HelpEquipmentRoute
  '/help/guides': typeof HelpGuidesRoute
  '/help/hardship': typeof HelpHardshipRoute
  '/help/health-safety': typeof HelpHealthSafetyRoute
  '/help/law': typeof HelpLawRoute
  '/help/pests': typeof HelpPestsRoute
  '/help/plant-health': typeof HelpPlantHealthRoute
  '/help/podcast': typeof HelpPodcastRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/magazine': typeof NewsMagazineRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/help/': typeof HelpIndexRoute
  '/news/': typeof NewsIndexRoute
  '/policy/': typeof PolicyIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/policy/$id': typeof AdminPolicyIdRoute
  '/admin/training/$id': typeof AdminTrainingIdRoute
  '/api/public/conference-interest': typeof ApiPublicConferenceInterestRoute
  '/api/public/membership-application': typeof ApiPublicMembershipApplicationRoute
  '/join/$category/apply': typeof JoinCategoryApplyRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/policy/': typeof AdminPolicyIndexRoute
  '/admin/training/': typeof AdminTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/contact'
    | '/join'
    | '/login'
    | '/portal'
    | '/about/awards'
    | '/admin/reset-password'
    | '/directory/contractor'
    | '/directory/designer'
    | '/directory/search'
    | '/directory/supplier'
    | '/directory/training'
    | '/directory/why'
    | '/events/$slug'
    | '/events/training'
    | '/help/contract'
    | '/help/dispute'
    | '/help/domestic-landscape-contract'
    | '/help/equipment'
    | '/help/guides'
    | '/help/hardship'
    | '/help/health-safety'
    | '/help/law'
    | '/help/pests'
    | '/help/plant-health'
    | '/help/podcast'
    | '/news/$slug'
    | '/news/magazine'
    | '/policy/$slug'
    | '/admin/'
    | '/directory/'
    | '/events/'
    | '/help/'
    | '/news/'
    | '/policy/'
    | '/admin/events/$id'
    | '/admin/news/$id'
    | '/admin/policy/$id'
    | '/admin/training/$id'
    | '/api/public/conference-interest'
    | '/api/public/membership-application'
    | '/join/$category/apply'
    | '/admin/events/'
    | '/admin/news/'
    | '/admin/policy/'
    | '/admin/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contact'
    | '/join'
    | '/login'
    | '/portal'
    | '/about/awards'
    | '/admin/reset-password'
    | '/directory/contractor'
    | '/directory/designer'
    | '/directory/search'
    | '/directory/supplier'
    | '/directory/training'
    | '/directory/why'
    | '/events/$slug'
    | '/events/training'
    | '/help/contract'
    | '/help/dispute'
    | '/help/domestic-landscape-contract'
    | '/help/equipment'
    | '/help/guides'
    | '/help/hardship'
    | '/help/health-safety'
    | '/help/law'
    | '/help/pests'
    | '/help/plant-health'
    | '/help/podcast'
    | '/news/$slug'
    | '/news/magazine'
    | '/policy/$slug'
    | '/admin'
    | '/directory'
    | '/events'
    | '/help'
    | '/news'
    | '/policy'
    | '/admin/events/$id'
    | '/admin/news/$id'
    | '/admin/policy/$id'
    | '/admin/training/$id'
    | '/api/public/conference-interest'
    | '/api/public/membership-application'
    | '/join/$category/apply'
    | '/admin/events'
    | '/admin/news'
    | '/admin/policy'
    | '/admin/training'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/contact'
    | '/join'
    | '/login'
    | '/portal'
    | '/about/awards'
    | '/admin/reset-password'
    | '/directory/contractor'
    | '/directory/designer'
    | '/directory/search'
    | '/directory/supplier'
    | '/directory/training'
    | '/directory/why'
    | '/events/$slug'
    | '/events/training'
    | '/help/contract'
    | '/help/dispute'
    | '/help/domestic-landscape-contract'
    | '/help/equipment'
    | '/help/guides'
    | '/help/hardship'
    | '/help/health-safety'
    | '/help/law'
    | '/help/pests'
    | '/help/plant-health'
    | '/help/podcast'
    | '/news/$slug'
    | '/news/magazine'
    | '/policy/$slug'
    | '/admin/'
    | '/directory/'
    | '/events/'
    | '/help/'
    | '/news/'
    | '/policy/'
    | '/admin/events/$id'
    | '/admin/news/$id'
    | '/admin/policy/$id'
    | '/admin/training/$id'
    | '/api/public/conference-interest'
    | '/api/public/membership-application'
    | '/join/$category/apply'
    | '/admin/events/'
    | '/admin/news/'
    | '/admin/policy/'
    | '/admin/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  JoinRoute: typeof JoinRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  AboutAwardsRoute: typeof AboutAwardsRoute
  DirectoryContractorRoute: typeof DirectoryContractorRoute
  DirectoryDesignerRoute: typeof DirectoryDesignerRoute
  DirectorySearchRoute: typeof DirectorySearchRoute
  DirectorySupplierRoute: typeof DirectorySupplierRoute
  DirectoryTrainingRoute: typeof DirectoryTrainingRoute
  DirectoryWhyRoute: typeof DirectoryWhyRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsTrainingRoute: typeof EventsTrainingRoute
  HelpContractRoute: typeof HelpContractRoute
  HelpDisputeRoute: typeof HelpDisputeRoute
  HelpDomesticLandscapeContractRoute: typeof HelpDomesticLandscapeContractRoute
  HelpEquipmentRoute: typeof HelpEquipmentRoute
  HelpGuidesRoute: typeof HelpGuidesRoute
  HelpHardshipRoute: typeof HelpHardshipRoute
  HelpHealthSafetyRoute: typeof HelpHealthSafetyRoute
  HelpLawRoute: typeof HelpLawRoute
  HelpPestsRoute: typeof HelpPestsRoute
  HelpPlantHealthRoute: typeof HelpPlantHealthRoute
  HelpPodcastRoute: typeof HelpPodcastRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsMagazineRoute: typeof NewsMagazineRoute
  PolicySlugRoute: typeof PolicySlugRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PolicyIndexRoute: typeof PolicyIndexRoute
  ApiPublicConferenceInterestRoute: typeof ApiPublicConferenceInterestRoute
  ApiPublicMembershipApplicationRoute: typeof ApiPublicMembershipApplicationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/': {
      id: '/policy/'
      path: '/policy'
      fullPath: '/policy/'
      preLoaderRoute: typeof PolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/policy/$slug': {
      id: '/policy/$slug'
      path: '/policy/$slug'
      fullPath: '/policy/$slug'
      preLoaderRoute: typeof PolicySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/magazine': {
      id: '/news/magazine'
      path: '/news/magazine'
      fullPath: '/news/magazine'
      preLoaderRoute: typeof NewsMagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/podcast': {
      id: '/help/podcast'
      path: '/help/podcast'
      fullPath: '/help/podcast'
      preLoaderRoute: typeof HelpPodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/plant-health': {
      id: '/help/plant-health'
      path: '/help/plant-health'
      fullPath: '/help/plant-health'
      preLoaderRoute: typeof HelpPlantHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/pests': {
      id: '/help/pests'
      path: '/help/pests'
      fullPath: '/help/pests'
      preLoaderRoute: typeof HelpPestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/law': {
      id: '/help/law'
      path: '/help/law'
      fullPath: '/help/law'
      preLoaderRoute: typeof HelpLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/health-safety': {
      id: '/help/health-safety'
      path: '/help/health-safety'
      fullPath: '/help/health-safety'
      preLoaderRoute: typeof HelpHealthSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/hardship': {
      id: '/help/hardship'
      path: '/help/hardship'
      fullPath: '/help/hardship'
      preLoaderRoute: typeof HelpHardshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/guides': {
      id: '/help/guides'
      path: '/help/guides'
      fullPath: '/help/guides'
      preLoaderRoute: typeof HelpGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/equipment': {
      id: '/help/equipment'
      path: '/help/equipment'
      fullPath: '/help/equipment'
      preLoaderRoute: typeof HelpEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/domestic-landscape-contract': {
      id: '/help/domestic-landscape-contract'
      path: '/help/domestic-landscape-contract'
      fullPath: '/help/domestic-landscape-contract'
      preLoaderRoute: typeof HelpDomesticLandscapeContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/dispute': {
      id: '/help/dispute'
      path: '/help/dispute'
      fullPath: '/help/dispute'
      preLoaderRoute: typeof HelpDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/contract': {
      id: '/help/contract'
      path: '/help/contract'
      fullPath: '/help/contract'
      preLoaderRoute: typeof HelpContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/training': {
      id: '/events/training'
      path: '/events/training'
      fullPath: '/events/training'
      preLoaderRoute: typeof EventsTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/why': {
      id: '/directory/why'
      path: '/directory/why'
      fullPath: '/directory/why'
      preLoaderRoute: typeof DirectoryWhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/training': {
      id: '/directory/training'
      path: '/directory/training'
      fullPath: '/directory/training'
      preLoaderRoute: typeof DirectoryTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/supplier': {
      id: '/directory/supplier'
      path: '/directory/supplier'
      fullPath: '/directory/supplier'
      preLoaderRoute: typeof DirectorySupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/search': {
      id: '/directory/search'
      path: '/directory/search'
      fullPath: '/directory/search'
      preLoaderRoute: typeof DirectorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/designer': {
      id: '/directory/designer'
      path: '/directory/designer'
      fullPath: '/directory/designer'
      preLoaderRoute: typeof DirectoryDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/contractor': {
      id: '/directory/contractor'
      path: '/directory/contractor'
      fullPath: '/directory/contractor'
      preLoaderRoute: typeof DirectoryContractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/awards': {
      id: '/about/awards'
      path: '/about/awards'
      fullPath: '/about/awards'
      preLoaderRoute: typeof AboutAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/training/': {
      id: '/admin/training/'
      path: '/training'
      fullPath: '/admin/training/'
      preLoaderRoute: typeof AdminTrainingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policy/': {
      id: '/admin/policy/'
      path: '/policy'
      fullPath: '/admin/policy/'
      preLoaderRoute: typeof AdminPolicyIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/join/$category/apply': {
      id: '/join/$category/apply'
      path: '/$category/apply'
      fullPath: '/join/$category/apply'
      preLoaderRoute: typeof JoinCategoryApplyRouteImport
      parentRoute: typeof JoinRoute
    }
    '/api/public/membership-application': {
      id: '/api/public/membership-application'
      path: '/api/public/membership-application'
      fullPath: '/api/public/membership-application'
      preLoaderRoute: typeof ApiPublicMembershipApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conference-interest': {
      id: '/api/public/conference-interest'
      path: '/api/public/conference-interest'
      fullPath: '/api/public/conference-interest'
      preLoaderRoute: typeof ApiPublicConferenceInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/training/$id': {
      id: '/admin/training/$id'
      path: '/training/$id'
      fullPath: '/admin/training/$id'
      preLoaderRoute: typeof AdminTrainingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policy/$id': {
      id: '/admin/policy/$id'
      path: '/policy/$id'
      fullPath: '/admin/policy/$id'
      preLoaderRoute: typeof AdminPolicyIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/$id': {
      id: '/admin/news/$id'
      path: '/news/$id'
      fullPath: '/admin/news/$id'
      preLoaderRoute: typeof AdminNewsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsIdRoute: typeof AdminEventsIdRoute
  AdminNewsIdRoute: typeof AdminNewsIdRoute
  AdminPolicyIdRoute: typeof AdminPolicyIdRoute
  AdminTrainingIdRoute: typeof AdminTrainingIdRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminPolicyIndexRoute: typeof AdminPolicyIndexRoute
  AdminTrainingIndexRoute: typeof AdminTrainingIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsIdRoute: AdminEventsIdRoute,
  AdminNewsIdRoute: AdminNewsIdRoute,
  AdminPolicyIdRoute: AdminPolicyIdRoute,
  AdminTrainingIdRoute: AdminTrainingIdRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminPolicyIndexRoute: AdminPolicyIndexRoute,
  AdminTrainingIndexRoute: AdminTrainingIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JoinRouteChildren {
  JoinCategoryApplyRoute: typeof JoinCategoryApplyRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinCategoryApplyRoute: JoinCategoryApplyRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  JoinRoute: JoinRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  AboutAwardsRoute: AboutAwardsRoute,
  DirectoryContractorRoute: DirectoryContractorRoute,
  DirectoryDesignerRoute: DirectoryDesignerRoute,
  DirectorySearchRoute: DirectorySearchRoute,
  DirectorySupplierRoute: DirectorySupplierRoute,
  DirectoryTrainingRoute: DirectoryTrainingRoute,
  DirectoryWhyRoute: DirectoryWhyRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsTrainingRoute: EventsTrainingRoute,
  HelpContractRoute: HelpContractRoute,
  HelpDisputeRoute: HelpDisputeRoute,
  HelpDomesticLandscapeContractRoute: HelpDomesticLandscapeContractRoute,
  HelpEquipmentRoute: HelpEquipmentRoute,
  HelpGuidesRoute: HelpGuidesRoute,
  HelpHardshipRoute: HelpHardshipRoute,
  HelpHealthSafetyRoute: HelpHealthSafetyRoute,
  HelpLawRoute: HelpLawRoute,
  HelpPestsRoute: HelpPestsRoute,
  HelpPlantHealthRoute: HelpPlantHealthRoute,
  HelpPodcastRoute: HelpPodcastRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsMagazineRoute: NewsMagazineRoute,
  PolicySlugRoute: PolicySlugRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  PolicyIndexRoute: PolicyIndexRoute,
  ApiPublicConferenceInterestRoute: ApiPublicConferenceInterestRoute,
  ApiPublicMembershipApplicationRoute: ApiPublicMembershipApplicationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
