/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AboutAwardsRouteImport } from './routes/about.awards'
import { Route as JoinCategoryApplyRouteImport } from './routes/join.$category.apply'
import { Route as ApiPublicMembershipApplicationRouteImport } from './routes/api/public/membership-application'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAwardsRoute = AboutAwardsRouteImport.update({
  id: '/about/awards',
  path: '/about/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCategoryApplyRoute = JoinCategoryApplyRouteImport.update({
  id: '/$category/apply',
  path: '/$category/apply',
  getParentRoute: () => JoinRoute,
} as any)
const ApiPublicMembershipApplicationRoute =
  ApiPublicMembershipApplicationRouteImport.update({
    id: '/api/public/membership-application',
    path: '/api/public/membership-application',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/about/awards': typeof AboutAwardsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/membership-application': typeof ApiPublicMembershipApplicationRoute
  '/join/$category/apply': typeof JoinCategoryApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/about/awards': typeof AboutAwardsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/events': typeof EventsIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/public/membership-application': typeof ApiPublicMembershipApplicationRoute
  '/join/$category/apply': typeof JoinCategoryApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/about/awards': typeof AboutAwardsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/membership-application': typeof ApiPublicMembershipApplicationRoute
  '/join/$category/apply': typeof JoinCategoryApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/contact'
    | '/join'
    | '/login'
    | '/portal'
    | '/about/awards'
    | '/events/$slug'
    | '/news/$slug'
    | '/events/'
    | '/news/'
    | '/api/public/membership-application'
    | '/join/$category/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contact'
    | '/join'
    | '/login'
    | '/portal'
    | '/about/awards'
    | '/events/$slug'
    | '/news/$slug'
    | '/events'
    | '/news'
    | '/api/public/membership-application'
    | '/join/$category/apply'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/contact'
    | '/join'
    | '/login'
    | '/portal'
    | '/about/awards'
    | '/events/$slug'
    | '/news/$slug'
    | '/events/'
    | '/news/'
    | '/api/public/membership-application'
    | '/join/$category/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ContactRoute: typeof ContactRoute
  JoinRoute: typeof JoinRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  AboutAwardsRoute: typeof AboutAwardsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiPublicMembershipApplicationRoute: typeof ApiPublicMembershipApplicationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/awards': {
      id: '/about/awards'
      path: '/about/awards'
      fullPath: '/about/awards'
      preLoaderRoute: typeof AboutAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$category/apply': {
      id: '/join/$category/apply'
      path: '/$category/apply'
      fullPath: '/join/$category/apply'
      preLoaderRoute: typeof JoinCategoryApplyRouteImport
      parentRoute: typeof JoinRoute
    }
    '/api/public/membership-application': {
      id: '/api/public/membership-application'
      path: '/api/public/membership-application'
      fullPath: '/api/public/membership-application'
      preLoaderRoute: typeof ApiPublicMembershipApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JoinRouteChildren {
  JoinCategoryApplyRoute: typeof JoinCategoryApplyRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinCategoryApplyRoute: JoinCategoryApplyRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ContactRoute: ContactRoute,
  JoinRoute: JoinRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  AboutAwardsRoute: AboutAwardsRoute,
  EventsSlugRoute: EventsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiPublicMembershipApplicationRoute: ApiPublicMembershipApplicationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
