
UPDATE public.events SET booking_url = 'https://www.bali.org.uk/events/supplier-forum-event-the-way-of-the-modern-world-how-to-build-a-7016/' WHERE slug = 'supplier-forum-event-the-way-of-the-modern-world-how-to-build-a-7016';
UPDATE public.events SET booking_url = 'https://www.bali.org.uk/events/bali-chalk-open-mic-night-7157/', description = 'The BALI Chalk team is hosting an Open Mic event at the Spice of Life Bar, Soho on 1 October.' WHERE slug = 'bali-chalk-open-mic-night-7157';

INSERT INTO public.events (slug, title, date_text, iso_date, venue, category, description, booking_url, published, sort_order)
VALUES
('get-more-from-your-bali-membership-7177', 'Get more from your BALI membership', '28 Jul 2026', '2026-07-28', 'Online', 'Webinar', 'Join our online session to learn how to make the most of your BALI membership.', 'https://www.bali.org.uk/events/get-more-from-your-bali-membership-7177/', true, 100),
('south-west-cornwall-regional-connect-7191', 'South West Cornwall Regional Connect', '28 Jul 2026', '2026-07-28', 'The Working Boat Pub', 'BALI Regional Event', 'South West regional connect event in Cornwall.', 'https://www.bali.org.uk/events/south-west-cornwall-regional-connect-7191/', true, 99),
('get-more-from-your-bali-membership-7198', 'Get more from your BALI membership', '01 Sep 2026', '2026-09-01', 'Online', 'Webinar', 'Join our online session to learn how to make the most of your BALI membership.', 'https://www.bali.org.uk/events/get-more-from-your-bali-membership-7198/', true, 98),
('south-thames-goodwood-art-foundation-event-7189', 'South Thames Goodwood Art Foundation Event', '04 Sep 2026', '2026-09-04', 'Goodwood Art Foundation', 'BALI Regional Event', 'South Thames regional event at the Goodwood Art Foundation.', 'https://www.bali.org.uk/events/south-thames-goodwood-art-foundation-event-7189/', true, 97),
('north-thames-natural-history-museum-event-7196', 'North Thames Natural History Museum Event', '08 Sep 2026', '2026-09-08', 'Natural History Museum', 'BALI Regional Event', 'North Thames regional event at the Natural History Museum.', 'https://www.bali.org.uk/events/north-thames-natural-history-museum-event-7196/', true, 96),
('midlands-jack-moody-landscaping-and-civil-engineering-event-7187', 'Midlands Jack Moody Group Event', '24 Sep 2026', '2026-09-24', 'Jack Moody Group', 'BALI Regional Event', 'Midlands regional event hosted by the Jack Moody Group.', 'https://www.bali.org.uk/events/midlands-jack-moody-landscaping-and-civil-engineering-event-7187/', true, 95),
('get-more-from-your-bali-membership-7205', 'Get more from your BALI membership', '29 Sep 2026', '2026-09-29', 'Online', 'Webinar', 'Join our online session to learn how to make the most of your BALI membership.', 'https://www.bali.org.uk/events/get-more-from-your-bali-membership-7205/', true, 94),
('get-more-from-your-bali-membership-7202', 'Get more from your BALI membership', '27 Oct 2026', '2026-10-27', 'Online', 'Webinar', 'Join our online session to learn how to make the most of your BALI membership.', 'https://www.bali.org.uk/events/get-more-from-your-bali-membership-7202/', true, 93),
('get-more-from-your-bali-membership-7203', 'Get more from your BALI membership', '17 Nov 2026', '2026-11-17', 'Online', 'Webinar', 'Join our online session to learn how to make the most of your BALI membership.', 'https://www.bali.org.uk/events/get-more-from-your-bali-membership-7203/', true, 92),
('get-more-from-your-bali-membership-7204', 'Get more from your BALI membership', '15 Dec 2026', '2026-12-15', 'Online', 'Webinar', 'Join our online session to learn how to make the most of your BALI membership.', 'https://www.bali.org.uk/events/get-more-from-your-bali-membership-7204/', true, 91)
ON CONFLICT (slug) DO UPDATE SET booking_url = EXCLUDED.booking_url, category = EXCLUDED.category, venue = EXCLUDED.venue, date_text = EXCLUDED.date_text, iso_date = EXCLUDED.iso_date;
